language: cpp
compiler: gcc
os: linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov

before_install:
    - ./install_dependencies.sh

script:
    - ./build.sh

after_success:
    - ./coverage.sh

