language: cpp
compiler: gcc
os: linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov

before_install:
    - sudo wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
    - sudo tar xzvf release-1.8.0.tar.gz
    - cd googletest-release-1.8.0
    - sudo cmake -DBUILD_SHARED_LIBS=ON .
    - sudo make
    - sudo make install
    - sudo apt-get install libboost-all-dev
    - sudo apt-get -y install python-pip
    - sudo pip install -U pytest
    - python --version
    - cd "${TRAVIS_BUILD_DIR}"

script:
    - ./build.sh

after_success:
# Creating report
    - cd ${TRAVIS_BUILD_DIR}/tst/
    - echo `pwd`
    - lcov --directory itst/ --capture --output-file coverage_itst.info # capture coverage info
    - lcov --directory utst/ --capture --output-file coverage_utst.info # capture coverage info
    - lcov --add-tracefile coverage_itst.info --add-tracefile coverage_utst.info --output-file coverage_total.info #combining tracefiles
    - lcov --remove coverage_total.info '/usr/*' --output-file coverage_total.info # filter out system
    - path=`pwd`
    - utst_path=${path}/utst/*
    - utst_path1=${path}/utst/RequestsTests.cpp
    - itst_path=${path}/itst/*
    - lcov --remove coverage_total.info $utst_path --output-file coverage_total.info # filter out system
    - lcov --remove coverage_total.info $utst_path1 --output-file coverage_total.info # filter out system
    - lcov --remove coverage_total.info $itst_path --output-file coverage_total.info # filter out system
    - lcov --list coverage_total.info #debug info
    - echo $utst_path
    - echo $utst_path1
    - echo $itst_path
    # Uploading report to CodeCov
    - bash <(curl -s https://codecov.io/bash) -t c129d72a-3721-47cb-98e9-2b95cc643ea0 || echo "Codecov did not collect coverage reports"

